{% set name = "pybufrkit" %}
{% set version = "0.2.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pybufrkit-{{ version }}.tar.gz
  sha256: 87200614d7115fffda8e56f15052af6aa6ac3d065a442e5df48ce33392c2dbbd

build:
  entry_points:
    - pybufrkit = pybufrkit:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - pytest-runner
    - pip
  run:
    - python >=3.5
    - bitstring >=3.1.3
    - six

test:
  imports:
    - pybufrkit
  commands:
    - pip check
    - pybufrkit --help
  requires:
    - pip

about:
  home: https://github.com/ywangd/pybufrkit
  summary: Python toolkit to work with BUFR files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
