{% set name = "pybufrkit" %}
{% set version = "0.2.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pybufrkit-{{ version }}.tar.gz
  sha256: eca84571baf65b791b281ad8cb791d426d4a9f7b39d5b94f095fab76e9ccdfcc

build:
  entry_points:
    - pybufrkit = pybufrkit:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pytest-runner
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - bitstring >=3.1.3
    - six

test:
  imports:
    - pybufrkit
  commands:
    - pip check
    - pybufrkit --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ywangd/pybufrkit
  summary: Python toolkit to work with BUFR files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
